### ISSUE TITLE
Roundabout button is instantiated 2 times

### ISSUE THREAD

**Issue by kianzarrin** [Strdate/AutomaticRoundaboutBuilder#18]
When you use the Road Tool  for the first time, all buttons in `RoadOptionsPanel` are cloned into `RoadOptionsPanel(RoadOptions)`. I know it strange but that's what happening.

This can cause problem with some external mods like `More Shortcuts` or another mod I like to create to unite buttons in the RoadOptionsPanel.

```c#
// This is stack trace for NodeControllerButton which is similar to roundabout. the button is cloned after I click on the Roads button leading to a duplicate copy.
NodeControllerButton.Awake() is called.   at System.Environment.get_StackTrace()
   at NodeController.GUI.NodeControllerButton.Awake()
   at UnityEngine.Object.Internal_CloneSingle(UnityEngine.Object )
   at UnityEngine.Object.Instantiate(ColossalFramework.UI.UIComponent original) in C:\buildslave\unity\build\Runtime\Export\UnityEngineObject.cs:line 201
   at GeneratedScrollPanel.CreateOptionPanel(System.String templateName)
   at GeneratedScrollPanel.ShowRoadsOptionPanel()
   at RoadsPanel.OnButtonClicked(ColossalFramework.UI.UIComponent comp)
   at GeneratedScrollPanel.OnClick(ColossalFramework.UI.UIComponent comp, ColossalFramework.UI.UIMouseEventParameter p)
   at System.Reflection.MonoMethod.InternalInvoke(System.Object , System.Object[] , System.Exception ByRef )
   at System.Reflection.MonoMethod.Invoke(System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(System.Object obj, System.Object[] parameters)
   at ColossalFramework.UI.UIComponent.Invoke(UnityEngine.GameObject target, System.String eventName, System.Object[] args)
   at ColossalFramework.UI.UIComponent.Invoke(System.String eventName, System.Object[] args)
   at ColossalFramework.UI.UIComponent.OnClick(ColossalFramework.UI.UIMouseEventParameter p)
   at ColossalFramework.UI.UIComponent.OnClick(ColossalFramework.UI.UIMouseEventParameter p)
   at ColossalFramework.UI.UIComponent.OnClick(ColossalFramework.UI.UIMouseEventParameter p)
   at ColossalFramework.UI.UIButton.OnClick(ColossalFramework.UI.UIMouseEventParameter p)
   at ColossalFramework.UI.UIComponent.SimulateClick()
   at GeneratedScrollPanel.OnVisibilityChanged(ColossalFramework.UI.UIComponent comp, Boolean isVisible)
   at System.Reflection.MonoMethod.InternalInvoke(System.Object , System.Object[] , System.Exception ByRef )
   at System.Reflection.MonoMethod.Invoke(System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(System.Object obj, System.Object[] parameters)
   at ColossalFramework.UI.UIComponent.Invoke(UnityEngine.GameObject target, System.String eventName, System.Object[] args)
   at ColossalFramework.UI.UIComponent.Invoke(System.String eventName, System.Object[] args)
   at ColossalFramework.UI.UIComponent.OnVisibilityChanged()
   at ColossalFramework.UI.UIComponent.set_isVisible(Boolean value)
   at ColossalFramework.UI.UITabContainer.SelectPageByIndex(Int32 value)
   at ColossalFramework.UI.UITabContainer.set_selectedIndex(Int32 value)
   at ColossalFramework.UI.UITabstrip.SelectTabByIndex(Int32 value)
   at ColossalFramework.UI.UITabstrip.set_selectedIndex(Int32 value)
   at GeneratedGroupPanel.OnVisibilityChanged(ColossalFramework.UI.UIComponent comp, Boolean isVisible)
   at System.Reflection.MonoMethod.InternalInvoke(System.Object , System.Object[] , System.Exception ByRef )
   at System.Reflection.MonoMethod.Invoke(System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(System.Object obj, System.Object[] parameters)
   at ColossalFramework.UI.UIComponent.Invoke(UnityEngine.GameObject target, System.String eventName, System.Object[] args)
   at ColossalFramework.UI.UIComponent.Invoke(System.String eventName, System.Object[] args)
   at ColossalFramework.UI.UIComponent.OnVisibilityChanged()
   at ColossalFramework.UI.UIComponent.set_isVisible(Boolean value)
   at ColossalFramework.UI.UITabContainer.SelectPageByIndex(Int32 value)
   at ColossalFramework.UI.UITabContainer.set_selectedIndex(Int32 value)
   at ColossalFramework.UI.UITabstrip.SelectTabByIndex(Int32 value)
   at ColossalFramework.UI.UITabstrip.set_selectedIndex(Int32 value)
   at ColossalFramework.UI.UITabstrip.OnClick(ColossalFramework.UI.UIMouseEventParameter p)
   at ColossalFramework.UI.UIComponent.OnClick(ColossalFramework.UI.UIMouseEventParameter p)
   at ColossalFramework.UI.UIButton.OnClick(ColossalFramework.UI.UIMouseEventParameter p)
   at ColossalFramework.UI.UIInput+MouseHandler.ProcessInput(...)
   at ColossalFramework.UI.UIInput.ProcessMouseInput()
   at ColossalFramework.UI.UIInput.Update()
NodeControllerButton.Start() is called.
```

The only solution I found is to destroy the previous instant after button is cloned.
```c#
public override void Start() {
            if (Instace != null) {
                Destroy(Instace); // destroy old instance after cloning
            }
            Instace = this;
}
```

**Comment by Strdate** [comment]
What are the issues in particular?

**Comment by kianzarrin** [comment]
each UI gets events every frame so if every mod has redundancy it adds up.

Actually now that I think about it there is no other practical problem comes to mind but bad code has a tendency to cause unexpected problems.

**Comment by kianzarrin** [comment]
Actually I ran into problems when I remove the old button. :
```
NodeControllerButton.Awake() is called.   at System.Environment.get_StackTrace()
   at NodeController.GUI.NodeControllerButton.Awake()
   at UnityEngine.Object.Internal_CloneSingle(UnityEngine.Object )
   at UnityEngine.Object.Instantiate(ColossalFramework.UI.UIComponent original)
   at GeneratedScrollPanel.CreateOptionPanel(System.String templateName)
   at System.Reflection.MonoMethod.InternalInvoke(System.Object , System.Object[] , System.Exception ByRef )
   at System.Reflection.MonoMethod.Invoke(System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(System.Object obj, System.Object[] parameters)
   at AirportRoads.AirportRoads.InitMod()
   at AirportRoads.AirportRoads.OnLevelLoaded(LoadMode mode)
   at LoadingWrapper.DMD<DMD<OnLevelLoaded_Patch2>?918154496::OnLevelLoaded_Patch2>(.LoadingWrapper , UpdateMode )
   at LoadingManager+<LoadLevelComplete>c__Iterator9.MoveNext()
   at LoadingManager.Update()
```
Because of what the stack trace above button is not cloned to road options panel anymore.

So I closed the issue.
